on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      S3_BUCKET: "nix-s3-demo-1"
    steps:
      - uses: actions/checkout@v4
      - uses: arianvp/configure-aws@main
        with:
          role-arn: arn:aws:iam::686862074153:role/write-cache
          region: eu-central-1
      - run: echo "$NIX_PRIVATE_KEY" > /tmp/nix-secret-key
        env:
          NIX_PRIVATE_KEY: ${{ secrets.NIX_PRIVATE_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
        with:
         extra-conf: | 
           post-build-hook = ${{ github.workspace }}/post-build-hook.sh
      - run: nix run nixpkgs#awscli2 sts get-caller-identity
      - run: nix build --accept-flake-config