on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      S3_BUCKET: "nix-s3-demo-1"
    steps:
      - uses: actions/checkout@v4
      - run: echo "$NIX_PRIVATE_KEY" > /tmp/nix-secret-key
        env:
          NIX_PRIVATE_KEY: ${{ secrets.NIX_PRIVATE_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Set up AWS Credentials for current user
        uses: arianvp/configure-aws@main
        with:
          role-arn: arn:aws:iam::686862074153:role/write-cache
          region: eu-central-1
      - name: Set up AWS credentials for nix-daemon 
        uses: arianvp/configure-aws@main
        with:
          role-arn: arn:aws:iam::686862074153:role/read-cache
          region: eu-central-1
      - run: nix run nixpkgs#awscli2 sts get-caller-identity
      - run: nix build --accept-flake-config
      - run: nix copy --to 's3://cache20240224120542829900000001?region=eu-central-1&secret-key=/tmp/nix-secret-key'