on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      CACHE_BUCKET: "s3://${{ vars.CACHE_BUCKET }}?region=${{ vars.CACHE_BUCKET_REGION }}"
    steps:
      - uses: actions/checkout@v4
      - run: echo "$NIX_SECRET_KEY" > /tmp/nix-secret-key
        env:
          NIX_SECRET_KEY: ${{ secrets.NIX_SECRET_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Set up AWS Credentials for current user
        uses: arianvp/configure-aws-action@main
        with:
          role-arn: arn:aws:iam::686862074153:role/write-cache
          region: eu-central-1
      - name: Set up AWS credentials for nix-daemon 
        uses: arianvp/configure-aws-action@main
        with:
          role-arn: arn:aws:iam::686862074153:role/read-cache
          region: eu-central-1
          role-session-name: GithubActionsNixDaemon
          user: root
      - run: nix run nixpkgs#awscli2 sts get-caller-identity
      - run: sudo -i nix run nixpkgs#awscli2 sts get-caller-identity
      - run: nix build --extra-trusted-public-keys '${{ secrets.NIX_PUBLIC_KEY }}' --extra-substituters '${{ vars.CACHE_BUCKET_ARN }}'
      - run: nix sign --key-file  /tmp/nix-secret-key
      - run: nix copy --to '${{ env.S3_BUCKET }}'
